#!/usr/bin/python
import os
import sys

# Append Openshift deployment support libraries to system path
sys.path.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'libs', 'openshift'))

# Setup virtualenv
virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

# Configure the application (Logan)
from sentry.utils.runner import configure
os.environ['SENTRY_CONF'] = os.environ['OPENSHIFT_REPO_DIR'] + 'openshift.conf.py'
configure()

# Build the wsgi app
import django.core.handlers.wsgi

from django.conf import settings
from raven.contrib.django.middleware.wsgi import Sentry

if settings.SESSION_FILE_PATH and not os.path.exists(settings.SESSION_FILE_PATH):
    try:
        os.makedirs(settings.SESSION_FILE_PATH)
    except OSError:
        pass

# Run WSGI handler for the application
application = Sentry(django.core.handlers.wsgi.WSGIHandler())
